apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: demo-voting-app
    name: voting-service
spec: 
  type: LoadBalancer
  selector:
    app: demo-voting-app
    name: voting-app-pod
  ports:
  - port: 80
    targetPort: 80
